const getStyles = (lightMode) => ({
    container: {
      maxWidth: "1000px",
      margin: "0 auto",
      padding: "30px",
      borderRadius: "10px",
      boxShadow: "0 5px 10px rgba(0, 0, 0, 0.15)",
      textAlign: "center",
      fontFamily: "Arial, sans-serif",
      backgroundColor: lightMode ? "white" : "#232A35",
      width: "700px",
    },
    title: {
      fontSize: "26px",
      color: lightMode ? "black" : "white",
      marginBottom: "25px",
    },
    form: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
    },
    input: {
      backgroundColor: lightMode ? "#f0f4ff" : "#475368",
      width: "100%",
      padding: "14px",
      marginBottom: "16px",
      border: "1px solid #ccc",
      borderRadius: "6px",
      fontSize: "18px",
      outline: "none",
      color: lightMode ? "black" : "white",
    },
    select: {
      backgroundColor: lightMode ? "#f0f4ff" : "#475368",
      width: "100%",
      padding: "14px",
      marginBottom: "16px",
      border: "1px solid #ccc",
      borderRadius: "6px",
      fontSize: "18px",
      outline: "none",
      color: lightMode ? "black" : "rgb(213, 208, 208)",
    },
    textArea: {
      color: lightMode ? "black" : "white",
      backgroundColor: lightMode ? "#f0f4ff" : "#475368",
      width: "100%",
      padding: "14px",
      border: "1px solid #ccc",
      borderRadius: "6px",
      fontSize: "18px",
      height: "140px",
      resize: "none",
      outline: "none",
      marginBottom: "16px",
    },
    button: {
      width: "100%",
      background: "#007bff",
      color: lightMode ? "white" : "black",
      padding: "14px",
      border: "none",
      borderRadius: "6px",
      cursor: "pointer",
      fontSize: "18px",
      transition: "background 0.3s ease-in-out",
    },
  });
  
  export default getStyles;