const getStyles = (lightMode) => ({
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    background: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: "1000",
  },
  box: {
    position: "relative",
    width: "350px",
    padding: "30px",
    borderRadius: "10px",
    background: lightMode ? "#f0f4ff" : "#232A35",
    boxShadow: "0 5px 15px rgba(0, 0, 0, 0.2)",
    textAlign: "center",
    color: lightMode ? "black" : "white",
    height: "560px",
  },
  forgotPasswordLink: {
    fontSize: "12px",
    color: "#007bff",
    textDecoration: "none",
    marginTop: "2px",
    marginBottom: "15px",
    textAlign: "center",
  },  
  closeButton: {
    position: "absolute",
    top: "10px",
    right: "10px",
    background: "none",
    border: "none",
    fontSize: "20px",
    cursor: "pointer",
    color: lightMode ? "black" : "white",
  },
  heading: {
    marginBottom: "10px",
  },
  text: {
    fontSize: "14px",
  },
  tabs: {
    display: "flex",
    justifyContent: "space-between",
    margin: "20px 0",
  },
  tab: {
    flex: 1,
    padding: "10px",
    border: "none",
    background: "none",
    fontSize: "16px",
    fontWeight: "bold",
    cursor: "pointer",
    borderBottom: "2px solid transparent",
  },
  form: {
    display: "flex",
    flexDirection: "column",
  },
  input: {
    width: "100%",
    padding: "10px",
    margin: "8px 0",
    border: "1px solid #ccc",
    borderRadius: "5px",
    background: lightMode ? "white" : "#475368",
    color: lightMode ? "black" : "white",
  },
  button: {
    background: "#007bff",
    color: "white",
    border: "none",
    padding: "10px",
    borderRadius: "5px",
    cursor: "pointer",
    marginTop: "10px",
  },
  divider: {
    margin: "20px 0",
    fontSize: "14px",
    position: "relative",
  },
  socialLogin: {
    display: "flex",
    justifyContent: "center",
    gap: "15px",
    marginTop: "10px",
  },
  socialButton: {
    width: "40px",
    height: "40px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    border: "1px solid #ccc",
    cursor: "pointer",
    background: "white",
  },
  footerText: {
    fontSize: "12px",
    marginTop: "25px",
  },
  link: {
    color: "#007bff",
    textDecoration: "none",
  },
});

export default getStyles;